RHDM-1354: NPE creating a project using Decision Central REST API and githook configured
kiegroup/appformer pull request #1064
Opened 2020-10-21 13:30 UTC by akumar074

* Added HeaderParam to include accept-language in Rest calls for createProject

**Issue:** The issue is caused by a failure to get custom post-commit notification messages while using the REST API to create the project. Currently, messages are fetched with RpcContext which is not active in REST calls.
**Solution:** Added a HttpHeader option in REST API to set a Locale. If Locale isn't available in Header param, default Locale will be used to get the custom messages.

**JIRA**: [RHDM-1354](https://issues.redhat.com/browse/RHDM-1354)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

2020-10-27 12:20 UTC, akumar074 commented
Jenkins run fdb

2020-11-02 15:38 UTC, akumar074 commented
Jenkins run fdb

2020-11-02 15:38 UTC, akumar074 commented
Jenkins run cdb

2020-11-04 16:14 UTC, barboras7 approved these changes
The issue is fixed. Thanks @akumar074 !

2020-11-06 13:34 UTC, jesuino requested changes
Hello @akumar074 

The changes looks good, thanks!

Would you please modify the hardcoded strings to use constants instead?

Thanks!

2020-11-06 13:34 UTC, jesuino commented on uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/JobRequestScheduler.java
> +                   headers.get("acceptLanguage"));
I would avoid magic Strings and use a constant instead

2020-11-06 13:34 UTC, jesuino commented on uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/ProjectResource.java
> +            @HeaderParam("accept-language") Locale locales,
Wouldn't this constant be accept-language?

https://docs.oracle.com/javaee/7/api/javax/ws/rs/core/HttpHeaders.html#ACCEPT_LANGUAGE

2020-11-06 13:34 UTC, jesuino commented on uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/ProjectResource.java
> +        headers.put("acceptLanguage", locales);
same as before, please use a constant to avoid issues

2020-11-06 13:47 UTC, jesuino commented
Please also take a look at Sonar Cloud Code Smell

https://sonarcloud.io/project/issues?id=org.uberfire%3Auberfire-parent&pullRequest=1064&resolved=false&types=CODE_SMELL

2020-11-06 15:58 UTC, akumar074 commented
Jenkins run fdb

2020-11-06 16:19 UTC, akumar074 commented
Jenkins run fdb

2020-11-08 05:37 UTC, akumar074 commented
Jenkins run fdb

2020-11-08 05:38 UTC, akumar074 commented
Jenkins run cdb

2020-11-10 13:53 UTC, akumar074 commented
Jenkins run fdb

2020-11-10 13:53 UTC, akumar074 commented
Jenkins run fdb

2020-11-10 16:43 UTC, akumar074 commented
Jenkins run cdb

2020-11-12 11:16 UTC, akumar074 commented
Jenkins run cdb

2020-11-12 11:16 UTC, akumar074 commented
Jenkins run fdb

2020-11-12 16:00 UTC, jesuino approved these changes
LGTM - Thanks!

2020-11-16 14:05 UTC, merged