AF-2768: Add time series internal component
kiegroup/appformer pull request #1117
Opened 2021-03-18 13:02 UTC by manaswinidas

**Thank you for submitting this pull request**

**JIRA**: https://issues.redhat.com/browse/AF-2768

[link](https://www.example.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

2021-03-18 14:24 UTC, jesuino commented
Hello @sthundat and @caponetto 

Could you please review this PR from @manaswinidas ?

In this PR she brings a new component to Dashbuilder which can be specifically used with timeseries from Prometheus

You can find more about this component in this post: https://blog.kie.org/2021/03/time-series-component-for-dashbuilder.html

The new component will be in Business Central under "Reporting" category

Thanks!

2021-03-18 14:27 UTC, jesuino commented
jenkins execute cdb

2021-03-18 14:27 UTC, jesuino commented
jenkins execute fdb

2021-03-18 16:14 UTC, jesuino commented
ok to test

2021-03-18 16:14 UTC, jesuino commented
jenkins execute cdb

2021-03-18 16:14 UTC, jesuino commented
jenkins execute fdb

2021-03-18 21:12 UTC, jesuino commented
jenkins execute cdb

2021-03-19 08:43 UTC, sthundat commented
> Hello @sthundat and @caponetto
> 
> Could you please review this PR from @manaswinidas ?
> 
> In this PR she brings a new component to Dashbuilder which can be specifically used with timeseries from Prometheus
> 
> You can find more about this component in this post: https://blog.kie.org/2021/03/time-series-component-for-dashbuilder.html
> 
> The new component will be in Business Central under "Reporting" category
> 
> Thanks!

Hi @jesuino and @manaswinidas ,As I have some other priority tasks to complete I am reassigning this PR to @Srihari1192 
Thanks,
Savitha

2021-03-19 12:58 UTC, jesuino commented
jenkins execute cdb

2021-03-19 17:57 UTC, jesuino commented
jenkins execute cdb

2021-03-22 13:53 UTC, caponetto reviewed
Hi @manaswinidas, thanks for the PR!
I've left some comments, please check if they make sense.

2021-03-22 13:53 UTC, caponetto commented on dashbuilder/dashbuilder-shared/dashbuilder-js/packages/time-series-component/jest.config.js
> +module.exports = {
Please add the copyright header to this file.

2021-03-22 13:53 UTC, caponetto commented on dashbuilder/dashbuilder-shared/dashbuilder-js/packages/time-series-component/src/Chart.tsx
> +  processesoptions: Options;
```suggestion
  processesOptions: Options;
```

2021-03-22 13:53 UTC, caponetto commented on dashbuilder/dashbuilder-shared/dashbuilder-js/packages/time-series-component/src/Chart.tsx
> +  processesseries: SingleSeries[];
```suggestion
  processesSeries: SingleSeries[];
```

2021-03-22 13:53 UTC, caponetto commented on dashbuilder/dashbuilder-shared/dashbuilder-js/packages/time-series-component/src/Chart.tsx
> +    arrayseries.push(newseries);
```suggestion
  for (let i = 1; i < dataset.columns.length; i++) {
    arrayseries.push({
      name: dataset.columns[i].name,
      data: dataset.data.map((d: Array<string | number>) => +d[i])
    });
```

2021-03-22 13:53 UTC, caponetto commented on dashbuilder/dashbuilder-shared/dashbuilder-js/packages/time-series-component/src/Chart.tsx
> +    arrayseries.push(newseries);
```suggestion
    arrayseries.push({ name: i, data: newdata });
```
With this, you wouldn't need the variable `newseries`.

2021-03-22 13:53 UTC, caponetto commented on dashbuilder/dashbuilder-shared/dashbuilder-js/packages/time-series-component/src/Chart.tsx
> +  datum = dataset.data.map((d: Array<string | number>) => d[2]);
```suggestion
  let names: string[] = dataset.data.map((d: string[]) => d[1]);
  let datum: Array<string | number> = dataset.data.map((d: Array<string | number>) => d[2]);
  const newnames: string[] = [];
```

2021-03-23 07:34 UTC, Srihari1192 commented
@manaswinidas Please find the observations
1.Naming convention for **time-series-chart** is not unique than other components. Should be something like **Time Series Chart**

![Screenshot from 2021-03-23 12-37-25](https://user-images.githubusercontent.com/57942961/112107118-912e7280-8bd4-11eb-855d-12f82fa37bc4.png)

2.Font Style is not unique in the page for icon hover and "Download SVG ,Download PNG, Download CSV"

![Screenshot from 2021-03-23 12-44-13](https://user-images.githubusercontent.com/57942961/112107879-87f1d580-8bd5-11eb-8929-82840d4debf0.png)

3.Zoom In and Zoom out level is behaving differently for different datasets, Should be unique behavior.

4.Validation is not handled for "Chart Name" in Component Editor section, for Chart name with few special characters download csv is failing and also its appending other characters for download svg and png.

![image](https://user-images.githubusercontent.com/57942961/112108869-cfc52c80-8bd6-11eb-8d48-b405fdfecff5.png)


5.While Navigating page from Editor to Preview, Status Initializing is displaying intermittently.

![Screenshot from 2021-03-23 11-58-54](https://user-images.githubusercontent.com/57942961/112108322-0c445880-8bd6-11eb-95b0-12f4a1d0a21d.png)


6.Data coming from Prometheus data sets provider is reflecting after page refresh, its not reflecting as soon as data changes.

2021-03-23 18:11 UTC, jesuino commented
Hello @Srihari1192 

Thank you so much for your great review.

I have a feedback for some of your points: 

2: Unfortunately that the issue with external components and since we are using another chart library it won't have the same look and feel as the libraries used by BC - so it is not possible to change this at the moment;

5: It is expected to see "Initializing" at least one time when the chart is first opened, is this the case?

6: To setup real time you must enable data refresh, please see my post in "Step 3: Configuring filtering and data refresh"  section and let us know if it works.

https://blog.kie.org/2021/03/building-prometheus-dashboards-in-business-central.html

2021-03-24 11:33 UTC, Srihari1192 commented
> Hello @Srihari1192
> 
> Thank you so much for your great review.
> 
> I have a feedback for some of your points:
> 
> 2: Unfortunately that the issue with external components and since we are using another chart library it won't have the same look and feel as the libraries used by BC - so it is not possible to change this at the moment;
> 
> 5: It is expected to see "Initializing" at least one time when the chart is first opened, is this the case?
> 
> 6: To setup real time you must enable data refresh, please see my post in "Step 3: Configuring filtering and data refresh" section and let us know if it works.
> 
> https://blog.kie.org/2021/03/building-prometheus-dashboards-in-business-central.html

Hi @jesuino 
5.Yes the same scenario which you mentioned  "Initializing"  when chart is opening
6.Configured by enabling data refresh, it works fine and able to see real time data changes.
Thanks

2021-03-24 13:14 UTC, Srihari1192 commented
@manaswinidas @jesuino when we open Time series charts in  dashbuilder runtime from business central, page is displaying as "Not found"

![Screenshot from 2021-03-24 15-05-22](https://user-images.githubusercontent.com/57942961/112316176-de900a00-8cd0-11eb-9c27-c8ae720c48b0.png)

2021-03-24 17:39 UTC, manaswinidas commented
@caponetto @Srihari1192 I have addressed the requested changes. Let me know if I missed something. I have also added some extra options.

2021-03-24 17:49 UTC, jesuino commented
@Srihari1192 

About the Zoom issue, we found that it is a Apex Chart limitation. When zooming small set of data it behaves weirdly. We won't be able to fix this for this PR, but we can address it in a near future.

We are checking Dashbuilder Runtime issue - which is a blocker for this PR.

Thanks!

2021-03-24 17:51 UTC, jesuino commented
jenkins execute fdb

2021-03-25 00:24 UTC, jesuino requested changes
Hello Das,

The component looks great, thanks. I noticed two small issues:

1)  Due the chart name validation, now when I drag the chart, I immediately see an error. I suggest you to change the default chart name "New chart" to a valid one

![image](https://user-images.githubusercontent.com/359820/112400502-3f2a4180-8ce7-11eb-9167-5178c112092a.png)


2) I am seeing this "NaN" in the chart series popup, I don't remember seeing it before

![image](https://user-images.githubusercontent.com/359820/112400543-55380200-8ce7-11eb-993c-55c636227390.png)

Thanks!

2021-03-25 00:24 UTC, jesuino commented on dashbuilder/dashbuilder-shared/dashbuilder-js/packages/time-series-component/static/manifest.json
> +{
Hello @manaswinidas 

Please add the category "Reporting" here so it will show up under "Reporting" in Components pallet.

2021-03-25 00:52 UTC, jesuino commented
Hello @Srihari1192 

Thanks for your feedback.

I made a test with Dashbuilder Runtime and Time Series and it works for me, see:

![image](https://user-images.githubusercontent.com/359820/112402356-2885e980-8ceb-11eb-95b4-420902e412bf.png)

Please make sure you use the Dashbuilder Runtime built for this PR. An older version won't work because it won't contain the internal component in dashbuilder-js JAR therefore resulting in "Not Found"

2021-03-25 07:21 UTC, manaswinidas commented
@jesuino addressed the requested changes

2021-03-25 07:23 UTC, jesuino commented
jenkins execute fdb

2021-03-25 10:43 UTC, caponetto approved these changes

2021-03-25 10:53 UTC, caponetto commented
@manaswinidas @jesuino I believe this test failure is related to this PR. Can you please take a look?
```
org.dashbuilder.external.impl.ComponentLoaderImplTest.testLoadInternalComponents
expected:<3> but was:<4>
```

2021-03-25 12:56 UTC, jesuino commented
@caponetto thanks for spotting this, Das is fixing this test

2021-03-25 17:03 UTC, Srihari1192 commented
jenkins execute fdb

2021-03-26 11:18 UTC, Srihari1192 approved these changes

2021-03-26 13:16 UTC, jesuino approved these changes
LGTM!

2021-03-26 13:38 UTC, ederign approved these changes
LGMT nice work @manaswinidas

2021-03-26 13:39 UTC, merged