AF-2850: Create project rest api should include project name in the response
kiegroup/appformer pull request #1141
Opened 2021-05-11 06:34 UTC by akumar074

* Updated the JobStatus result with correct project name when the project is successfully created by REST

**JIRA**: 
[AF-2850](https://issues.redhat.com/browse/AF-2850)
[RHPAM-3519](https://issues.redhat.com/browse/RHPAM-3519)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

2021-05-12 14:07 UTC, akumar074 commented
Jenkins run fdb

2021-05-13 06:19 UTC, akumar074 commented
Jenkins run fdb

2021-05-15 11:20 UTC, akumar074 commented
Jenkins run fdb

2021-05-17 08:58 UTC, akumar074 commented
@barboras7 FDB test failure seems unrelated

2021-05-18 14:10 UTC, adrielparedes requested changes

2021-05-18 14:10 UTC, adrielparedes commented on uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/JobRequestHelper.java
> +            if (project == null) {
I think this part is not covered with a Unit Test, can we add that? Good job!

2021-05-19 09:20 UTC, barboras7 commented
Hi @akumar074,

from the Jira description:
If project with same name already available in space then '-1' is appended to project name. There is no way we can identify it from response.  Ideally, REST API should throw exception if project with same name is available or it should include project name in the response of above REST API.

_I tested with the business-central.war from the full downstream build, and this is what I am seeing:_

curl -X POST -u 'testadmin:admin1234;' -H 'Content-type: application/json' 'http://localhost:8080/business-central/rest/spaces/MySpace/projects' --data '{"name": "SampleProject", "groupId": "com.sample", "version": "1.0.0-SNAPSHOT", "description": "SampleProject"}'
{"**jobId":"1621410106629-1"**,"status":"APPROVED","spaceName":"MySpace",**"projectName":"SampleProject"**,"projectGroupId":"com.sample","projectVersion":"1.0.0-SNAPSHOT","description":"SampleProject"} 

$ curl -X POST -u 'testadmin:admin1234;' -H 'Content-type: application/json' 'http://localhost:8080/business-central/rest/spaces/MySpace/projects' --data '{"name": "SampleProject", "groupId": "com.sample", "version": "1.0.0-SNAPSHOT", "description": "SampleProject"}'
**{"jobId":"1621410122779-2"**,"status":"APPROVED","spaceName":"MySpace",**"projectName":"SampleProject"**,"projectGroupId":"com.sample","projectVersion":"1.0.0-SNAPSHOT","description":"SampleProject"}



_My understanding from the Jira description is that the customer would expect something like_

$ curl -X POST -u 'testadmin:admin1234;' -H 'Content-type: application/json' 'http://localhost:8080/business-central/rest/spaces/MySpace/projects' --data '{"name": "SampleProject", "groupId": "com.sample", "version": "1.0.0-SNAPSHOT", "description": "SampleProject"}'
**{"jobId":"1621410122779-2"**,"status":"APPROVED","spaceName":"MySpace",**"projectName":"SampleProject-2"**,"projectGroupId":"com.sample","projectVersion":"1.0.0-SNAPSHOT","description":"SampleProject"}

2021-05-19 11:17 UTC, akumar074 commented
@barboras7 The create-project REST endpoint schedules a job to create the project. This is an async operation. The response we get doesn't tell about the actual project name created but gives information about the job (Job ID and status). We can see the job status with another endpoint "/jobs/{job-id}". This fix adds the correct project name with a success message in the job status.
We mentioned the same in JIRA comments.

2021-05-19 13:04 UTC, barboras7 approved these changes

2021-05-19 13:16 UTC, barboras7 commented
Thanks @akumar074, I did not notice the comment. Thank you for explanation, approving the PR.

2021-05-24 08:13 UTC, akumar074 commented
Jenkins run fdb

2021-05-25 11:48 UTC, akumar074 commented
@adrielparedes FDB test failures looks unrelated to the change.

2021-05-26 13:19 UTC, adrielparedes approved these changes

2021-05-26 14:18 UTC, merged