KOGITO-6226 : Editor content sanitization
kiegroup/appformer pull request #1215
Opened 2021-11-15 14:25 UTC by RishiRajAnand

2021-11-16 14:47 UTC, ederign requested changes
Please wait for the results from an ongoing discussion on chat before merging this!

2021-11-29 21:44 UTC, ederign approved these changes

2021-11-29 21:45 UTC, ederign commented
@tomasdavidorg do you mind also doing a quick sanity check on this? If you need more context, please ping us on gchat.

2021-11-30 07:01 UTC, tomasdavidorg approved these changes

2021-11-30 07:01 UTC, tomasdavidorg reviewed
Looks good to me. I had a talk with @RishiRajAnand on the chat.

2021-12-02 15:17 UTC, merged