RHPAM-3954 :Import a project via SSH is not working over a proxy
kiegroup/appformer pull request #1223
Opened 2021-12-21 10:39 UTC by RishiRajAnand

- this adds a new system property (**org.uberfire.nio.git.proxy.type**) to choose between 3 proxy types i.e http, sock5, sock4.
- For ex: to connect to a proxy server on sock5 protocol and with host 127.0.0.1 and port 8888 it looks like this. 
**-Dorg.uberfire.nio.git.proxy.ssh.over.http=true -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=8888 -Dorg.uberfire.nio.git.proxy.type=sock5**

**Thank you for submitting this pull request**

**RHPAM-3954**: [_(please edit the JIRA link if it exists)_ ](https://issues.redhat.com/browse/RHPAM-3954)

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

2021-12-21 10:43 UTC, RishiRajAnand commented
Jenkins run fdb

2021-12-23 06:06 UTC, RishiRajAnand commented
Jenkins run fdb

2021-12-23 13:03 UTC, adrielparedes requested changes

2022-01-05 11:58 UTC, RishiRajAnand commented
Jenkins run fdb

2022-01-05 11:59 UTC, RishiRajAnand commented on uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitSSHConfigSessionFactory.java
> +        if (config.getProxyType().equals("sock5")) {
I have added the changes, Thanks

2022-01-05 14:25 UTC, adrielparedes approved these changes

2022-01-12 13:14 UTC, tomasdavidorg approved these changes
Thanks @RishiRajAnand . Tested and it looks good to me.

2022-01-13 12:51 UTC, RishiRajAnand commented
FDB errors are unrelated

2022-01-18 14:27 UTC, akumar074 commented
@adrielparedes @tomasdavidorg @pefernan @RishiRajAnand 
Hey guys, is this PR good to merge? As this issue targets 7.12.1 we will need to raise backport PR as well.

2022-01-19 07:56 UTC, tomasdavidorg commented
@akumar074 Looks good to me from my side.

2022-01-19 09:44 UTC, akumar074 commented
Thanks @tomasdavidorg 
@adrielparedes @pefernan Can you please merge this PR

2022-01-21 13:00 UTC, merged